services:
  user-service:
    build:
      context: ../../life-xp-user-service/life-xp-user-service-main
      dockerfile: Dockerfile
    image: life-xp-user-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - life-xp-net

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - life-xp-net

volumes:
  postgres_data:

networks:
  life-xp-net:
    external: true